import "../../public/assets/css/globals.css";

export const metadata = {
    title: "Fashion Store",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/assets/images/favicon.png" sizes="any" />
            </head>
            <body className='antialiased background-image:/assets/images/background.png' >
                {children}
            </body>
        </html>
    );
}
